[package]
name = "ollama-rust-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
serde_json = "1.0.140"
syn = { version = "2.0.104",  features = ["full"] }
